# Generated by Django 5.2.12 on 2026-03-22 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this affiliate link.",
                        max_length=200,
                    ),
                ),
                ("url", models.URLField(help_text="Full affiliate URL.")),
                (
                    "short_code",
                    models.SlugField(
                        help_text="Short code to reference in posts, e.g., {{aff:my-book}}.",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="affiliates/")),
                ("is_active", models.BooleanField(default=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="CSS class for category icon (e.g., fa-star)",
                        max_length=50,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories", "ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=270, unique=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="posts/%Y/%m/"),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short summary for SEO and cards.",
                        max_length=500,
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Main article content. Supports HTML."),
                ),
                (
                    "vedanta_quote",
                    models.TextField(
                        blank=True,
                        help_text="A Vedanta or philosophical quote to highlight alongside the post.",
                    ),
                ),
                (
                    "vedanta_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of the quote (e.g., Upanishads, Bhagavad Gita).",
                        max_length=200,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, help_text="SEO title (max 70 chars).", max_length=70
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars).",
                        max_length=160,
                    ),
                ),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Restrict to premium users."
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
            ],
            options={"ordering": ["-published_at", "-created_at"],},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={"ordering": ["created_at"],},
        ),
    ]
