# Generated by Django 5.2.10 on 2026-03-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_is_edited_userpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_raw",
            field=models.TextField(
                blank=True, help_text="Original plain text (auto-saved)."
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                help_text="Write plain text — it auto-formats to styled HTML. Or use HTML directly."
            ),
        ),
    ]
